
version: '3.8'

services:
  chegg-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chegg-arena
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
